### ISSUE TITLE
APn and APb

### ISSUE THREAD

**Issue by SCYF123** [haochenheheda/LVVIS#15]
the result.json contains a list like: [obj1, obj2, obj3 ,...], you just need to split the objects base on the catgeory_id into two group : base categories and novel categories. In this way, you could obtain two list like: [obj_b1, obj_b2, ...] and [obj_n1, obj_n2, ..].

_Originally posted by @haochenheheda in https://github.com/haochenheheda/LVVIS/issues/2#issuecomment-1705350846_
            Thank you for your work! I have encountered some problems in calculating the APn and APb of ytvis2019 and ytvis2021 datasets,  I would like to ask you for help. According to your suggestion, I divided the predicted json file into two json files according to categories and uploaded them to the website respectively to get their respective AP results. However, my result has always been AP=APn+APb, I found that the result you gave was not such a relationship, and I would like to ask you how to calculate the final APn and APb.

**Comment by haochenheheda** [comment]
You should modify the AP_b and AP_n by:
AP_b = AP_b  * (num_b + num_n) / num_b
AP_n = AP_n  * (num_b + num_n) / num_n
That is because the CodaLab will always output the result divided by the number of summations of base and novel categories.

**Comment by SCYF123** [comment]
I understand, thank you for your response.
