### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by fanghaook** [haochenheheda/LVVIS#2]
Thank you for sharing the code！I also have some questions to ask the author.

1. According to Baseline.md, I have reached the training stage: `sh scripts/train.sh`, an error occurred: 
```
No pretrained configuration specified for resnet50_in21k model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly. 
File "/home/LVVIS/ov2seg/modeling/backbone/timm.py", line 45, in __init__super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_cfg'
```
2. The author has released a training set for LVVIS, but Baseline has not trained the training set? If I want to train the LVVIS training set, how can I modify the code for training?
3. The code did not call the CLIP model because the metadata folder contains all the category CLIP features?
4. When will the model weight file be released?
Thanks！

**Comment by haochenheheda** [comment]
1. I guess it is because the version of timm. Please make sure your timm version to be 0.5.4.
2. In this paper, we did not use the training set. The LV-VIS training set has the same format as Youtube-VIS, you may follow works trained on Youtube-VIS to modify the code. In the meantime, we are developing video-trained model right now, which could be released in a few months.
3. Yes, the classifiers are pre-computed by this [repo](https://github.com/dyabel/detpro). We will clarify it in Readme.
4. It's released now.

**Comment by fanghaook** [comment]
Thank you for your answer! I still have some questions:

1. The annotation file I downloaded from the LVIS official website is lvis_v1_train.json, but in the author's configs, it is lvis_v1_train_norare.json, are these two files the same?
2. I would like to reproduce the author's results. May I know how to configure training hyperparameters, including IMS_ PER_ BATCH,BASE_LR,STEPS and MAX_ITER?
3. It seems that mAP.py can only test the performance of the LVVIS validation set. How can I test the performance of mAPn and mAPb for LVIS, LV-VIS (O), YTVIS, and OVIS? I can only test the mAP of the datasets. And for most datasets, the mAP I tested was about 1 AP lower than the results of the paper.
4. How to test fps?
I am very interested in your work, but I'm sorry there are many problems.

**Comment by haochenheheda** [comment]
1. please check [this](https://github.com/facebookresearch/Detic/blob/main/datasets/README.md)
2. Those hyperparameters are in the config file and the training script
3. For YTVIS, OVIS, you need to generate the result file and upload to according competition website [youtube-vis](https://codalab.lisn.upsaclay.fr/competitions/7680), [ovis](https://codalab.lisn.upsaclay.fr/competitions/4763).   [LV-VIS (O) and coco](https://github.com/haochenheheda/LVVIS/blob/main/scripts/eval_image.sh) . LVIS is automatically evaluated after training
4. fps is printed by detectron2 framework during evaluation.

**Comment by fanghaook** [comment]
Thank you, I know these websites and scripts can test AP, but I only saw mAP and didn't see mAPn and mAPb. What did I ignore?

**Comment by haochenheheda** [comment]
You need to generate two .json files. One contains base categories only, and another contains novel categories only. Then you could obtain mAPn and mAPb by uploading those two files respectivelty.

**Comment by fanghaook** [comment]
Sorry, actually I just wanted to ask how do I generate these two. json files?

**Comment by haochenheheda** [comment]
the result.json contains a list like: [obj1, obj2, obj3 ,...], you just need to split the objects base on the catgeory_id into two group : base categories and novel categories. In this way, you could obtain two list like: [obj_b1, obj_b2, ...] and [obj_n1, obj_n2, ..].

**Comment by fanghaook** [comment]
Sorry, I still don't know how to calculate the LVVIS Val dataset fps. The following is the printing by detectron2 framework during evaluation.
[d2.evaluation.evaluator]: Inference done 835/837. Dataloading: 0.0154 s/iter. Inference: 0.7600 s/iter. Eval: 5.4418 s/iter. Total: 6.2177 s/iter. ETA=0:00:12
[d2.evaluation.evaluator]: Inference done 836/837. Dataloading: 0.0154 s/iter. Inference: 0.7601 s/iter. Eval: 5.4421 s/iter. Total: 6.2181 s/iter. ETA=0:00:06
[d2.evaluation.evaluator]: Inference done 837/837. Dataloading: 0.0154 s/iter. Inference: 0.7601 s/iter. Eval: 5.4461 s/iter. Total: 6.2221 s/iter. ETA=0:00:00
[d2.evaluation.evaluator]: Total inference time: 1:26:16.922307 (6.222262 s / iter per device, on 1 devices)
[d2.evaluation.evaluator]: Total inference pure compute time: 0:10:32 (0.760074 s / iter per device, on 1 devices)

How to obtain 20.1 fps in the paper?

**Comment by yxchng** [comment]
@fanghaook Have you successfully generate the json files to evaluate YTVIS, OVIS? I am having trouble doing this too.

@haochenheheda Do you mind uploading the scripts to generate the files required for YTVIS, OVIS? Thanks.
