### ISSUE TITLE
About the category classification

### ISSUE THREAD

**Issue by renato-taka** [haochenheheda/LVVIS#4]
I‘d like to know how to divide the categories to base and novel.How can I get the lvis/lv_v1_train_norare.json flie?

**Comment by haochenheheda** [comment]
check [this](https://github.com/facebookresearch/Detic/blob/main/datasets/README.md).
```
python tools/remove_lvis_rare.py --ann datasets/lvis/lvis_v1_train.json
```

**Comment by renato-taka** [comment]
Thank you
