### ISSUE TITLE
No such file or directory: 'datasets/lvis/lvis_v1_train_norare.json'

### ISSUE THREAD

**Issue by yxchng** [haochenheheda/LVVIS#9]
I follow the baseline.md instruction but faces `No such file or directory: 'datasets/lvis/lvis_v1_train_norare.json'` error when trying to train the model. How can I resolve this error?

**Comment by haochenheheda** [comment]
Please check this file https://github.com/facebookresearch/Detic/blob/main/datasets/README.md.
```
python tools/remove_lvis_rare.py --ann datasets/lvis/lvis_v1_train.json
```
